Repository softwartechnik/lucifer-rising, pull requests merged in 2019-10, with the labels that each got.

#1 add editorconfig
  .editorconfig
Labels: documentation, enhancement

#2 Create README.md
  README.md
Labels: documentation

#3 Minify gradle build configuration
  build.gradle
Labels: documentation, enhancement

#5 Add Docker configuration files
  .dockerignore
  Dockerfile
  docker-compose.yml
Labels: enhancement

#7 Create FUNDING.yml
  .github/FUNDING.yml
Labels: documentation, enhancement

#10 Create CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: documentation, enhancement

#9 Create CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation, enhancement

#13 Update build.gradle
  build.gradle
Labels: enhancement

#12 Create SECURITY.md
  SECURITY.md
Labels: enhancement

#14 add SonarQube
  .travis.yml
  build.gradle
Labels: enhancement

#15 update Gradle
  gradle/wrapper/gradle-wrapper.properties
Labels: enhancement
