Repository softwartechnik/lucifer-rising, pull requests merged in 2020-02, with the labels that each got.

#59 Feature/user
  lucifer-rising-user/src/main/java/de/softwartechnik/lucifer/user/User.java
  lucifer-rising-user/src/main/java/de/softwartechnik/lucifer/user/UserService.java
  lucifer-rising-user/src/test/java/de/softwartechnik/lucifer/user/UserServiceTest.java
Labels: enhancement

#62 Feature/game statistics
  lucifer-rising-client/src/main/java/de/softwartechnik/lucifer/client/GameStatistics.java
  lucifer-rising-ear/META-INF/application.xml
  lucifer-rising-user/src/main/java/de/softwartechnik/lucifer/statistics/GameStatisticsBean.java
  lucifer-rising-user/src/main/java/de/softwartechnik/lucifer/user/UserDao.java
  lucifer-rising-user/src/main/java/de/softwartechnik/lucifer/user/UserService.java
Labels: enhancement

#61 Feature/messages
  lucifer-rising-chat/src/main/java/de/softwartechnik/lucifer/messaging/MessageBean.java
  lucifer-rising-chat/src/main/java/de/softwartechnik/lucifer/tree/MessageBean.java
  lucifer-rising-client/src/main/java/Messaging.java
  lucifer-rising-ear/META-INF/application.xml
Labels: enhancement

#63 Remove legacy game module deployment
  lucifer-rising-ear/lucifer-rising-ear.gradle
Labels: bug

#65 remove .gitkeep
  docs/.gitkeep
Labels: enhancement

#71 Properly construct session
  lucifer-rising-chat/src/test/java/de/softwartechnik/lucifer/tree/ChatSessionTest.java
  lucifer-rising-session/src/main/java/de/softwartechnik/lucifer/session/game/Game.java
  lucifer-rising-session/src/main/java/de/softwartechnik/lucifer/session/game/Games.java
  lucifer-rising-session/src/main/java/de/softwartechnik/lucifer/session/message/ChatMessages.java
Labels: bug, dependencies, documentation, duplicate, enhancement, good first issue, help wanted, invalid, question, wontfix

#72 Feature/menu view
  lucifer-rising-gui/src/main/java/de/softwartechnik/lucifer/gui/swing/controller/Controller.java
  lucifer-rising-gui/src/main/java/de/softwartechnik/lucifer/gui/swing/view/LoginPanel.java
  lucifer-rising-gui/src/main/java/de/softwartechnik/lucifer/gui/swing/view/MenuPanel.java
  lucifer-rising-gui/src/main/java/de/softwartechnik/lucifer/gui/swing/view/MenuView.java
  lucifer-rising-gui/src/main/java/de/softwartechnik/lucifer/gui/swing/view/Scenario.form
  lucifer-rising-gui/src/main/java/de/softwartechnik/lucifer/gui/swing/view/Scenario.java
  lucifer-rising-gui/src/main/java/de/softwartechnik/lucifer/gui/swing/view/Scenarioselection.form
  lucifer-rising-gui/src/main/java/de/softwartechnik/lucifer/gui/swing/view/Scenarioselection.java
  lucifer-rising-gui/src/main/java/de/softwartechnik/lucifer/gui/swing/view/SignUpPanel.java
  lucifer-rising-gui/src/main/java/de/softwartechnik/lucifer/gui/swing/view/SignUpView.java
  lucifer-rising-gui/src/main/java/de/softwartechnik/lucifer/gui/swing/view/Signup.form
  lucifer-rising-gui/src/main/java/de/softwartechnik/lucifer/gui/swing/view/Signup.java
Labels: enhancement

#73 Feature/scenario
  lucifer-rising-gui/src/main/java/de/softwartechnik/lucifer/gui/swing/controller/Controller.java
  lucifer-rising-gui/src/main/java/de/softwartechnik/lucifer/gui/swing/view/MainFrame.java
  lucifer-rising-gui/src/main/java/de/softwartechnik/lucifer/gui/swing/view/ScenarioPanel.java
  lucifer-rising-gui/src/main/java/de/softwartechnik/lucifer/gui/swing/view/ScenarioView.java
  lucifer-rising-gui/src/main/resources/scull_background.jpg
Labels: enhancement

#77 remove duplicate method
  lucifer-rising-session/src/main/java/de/softwartechnik/lucifer/session/SessionRegistry.java
Labels: bug

#76 Feature/gui
  lucifer-rising-client/src/main/java/de/softwartechnik/lucifer/client/Messaging.java
  lucifer-rising-gui/lucifer-rising-gui.gradle
  lucifer-rising-gui/src/main/java/de/softwartechnik/lucifer/gui/Login.form
  lucifer-rising-gui/src/main/java/de/softwartechnik/lucifer/gui/Login.java
  lucifer-rising-gui/src/main/java/de/softwartechnik/lucifer/gui/Scenario.form
  lucifer-rising-gui/src/main/java/de/softwartechnik/lucifer/gui/Scenario.java
  lucifer-rising-gui/src/main/java/de/softwartechnik/lucifer/gui/Scenarioselection.form
  lucifer-rising-gui/src/main/java/de/softwartechnik/lucifer/gui/Scenarioselection.java
  lucifer-rising-gui/src/main/java/de/softwartechnik/lucifer/gui/Signup.form
  lucifer-rising-gui/src/main/java/de/softwartechnik/lucifer/gui/Signup.java
  lucifer-rising-gui/src/main/java/de/softwartechnik/lucifer/gui/swing/SwingGui.java
  lucifer-rising-gui/src/main/java/de/softwartechnik/lucifer/gui/swing/controller/Controller.java
  lucifer-rising-gui/src/main/java/de/softwartechnik/lucifer/gui/swing/view/LoginPanel.java
  lucifer-rising-gui/src/main/java/de/softwartechnik/lucifer/gui/swing/view/LoginView.java
  lucifer-rising-gui/src/main/java/de/softwartechnik/lucifer/gui/swing/view/MainFrame.java
  lucifer-rising-gui/src/main/java/de/softwartechnik/lucifer/gui/swing/view/MenuPanel.java
  lucifer-rising-gui/src/main/java/de/softwartechnik/lucifer/gui/swing/view/MenuView.java
  lucifer-rising-gui/src/main/java/de/softwartechnik/lucifer/gui/swing/view/ScenarioPanel.java
  lucifer-rising-gui/src/main/java/de/softwartechnik/lucifer/gui/swing/view/ScenarioView.java
  lucifer-rising-gui/src/main/java/de/softwartechnik/lucifer/gui/swing/view/SignUpPanel.java
  lucifer-rising-gui/src/main/java/de/softwartechnik/lucifer/gui/swing/view/SignUpView.java
  lucifer-rising-gui/src/main/java/de/softwartechnik/lucifer/gui/swing/view/View.java
  lucifer-rising-gui/src/main/resources/scull_background.jpg
Labels: enhancement

#78 Feature/message client
  README.md
  lucifer-rising-client/src/main/java/de/softwartechnik/lucifer/client/Messaging.java
  lucifer-rising-gui/src/main/java/de/softwartechnik/lucifer/gui/swing/SwingGui.java
  lucifer-rising-gui/src/main/java/de/softwartechnik/lucifer/gui/swing/view/LoginPanel.java
  lucifer-rising-gui/src/main/java/de/softwartechnik/lucifer/gui/swing/view/LoginView.java
  lucifer-rising-gui/src/main/java/de/softwartechnik/lucifer/gui/swing/view/MenuPanel.java
  lucifer-rising-gui/src/main/java/de/softwartechnik/lucifer/gui/swing/view/MenuView.java
  lucifer-rising-gui/src/main/java/de/softwartechnik/lucifer/gui/swing/view/ScenarioPanel.java
  lucifer-rising-gui/src/main/java/de/softwartechnik/lucifer/gui/swing/view/ScenarioView.java
  lucifer-rising-gui/src/main/java/de/softwartechnik/lucifer/gui/swing/view/SignUpPanel.java
  lucifer-rising-gui/src/main/java/de/softwartechnik/lucifer/gui/swing/view/SignUpView.java
Labels: enhancement
